### ISSUE TITLE
一处错误和一处建议

### ISSUE THREAD

**Issue by wanlp10** [qpalzmqaz123/angular-pagination#1]
1,可以创建一个pagination.html用来存放html模板，并去掉指令中的template，加上templateUrl:'./pagination.html' 
2, 原理的指令js中template最后一个div闭合标签写错了，将"&lt;/div&gt;"写成了“&lt;div&gt;”

**Comment by qpalzmqaz123** [comment]
谢谢您的建议，html 标签的 bug 已解决。
对于 template 我没有单独放入 html 文件是因为 url 的相对路径取决于访问的 html 的路径而非当前组件的路径，所以容易出现找不到 templateUrl 的情况，为了简单起见直接放 template 里了。
